name: HACS

on:
  push:
    branches:
      - master
      - main
      - bscpylgtv-integration
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  hacs:
    name: HACS Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: HACS Validation
        uses: hacs/action@main
        with:
          category: integration
